name: Tracker
    
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: execute py script # run the run.py to get the latest data
        run: |
          pip install PyGithub
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          python python/grh.py
        env:
          REPO_NAME: 'github-release-history'
          REPO_USER: 'm2themax'
          API_KEY: ${{ secrets.api_key }}
